#!/usr/bin/env bash
# build-zipapp.sh — Build dist/openstation zipapp with baked version.
#
# Reads the version from pyproject.toml, generates _version.py,
# then creates a zipapp at dist/openstation.
#
# Usage:
#   bash scripts/build-zipapp.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="${REPO_ROOT}/src/openstation"
DIST_DIR="${REPO_ROOT}/dist"
VERSION_FILE="${SRC_DIR}/_version.py"

# --- Extract version from pyproject.toml ------------------------------------

VERSION=$(python3 -c "
import re, pathlib
text = pathlib.Path('${REPO_ROOT}/pyproject.toml').read_text()
m = re.search(r'^version\s*=\s*\"([^\"]+)\"', text, re.MULTILINE)
print(m.group(1))
")

if [[ -z "$VERSION" ]]; then
  echo "error: could not extract version from pyproject.toml" >&2
  exit 1
fi

printf 'Building zipapp for openstation %s\n' "$VERSION"

# --- Generate _version.py --------------------------------------------------

cat > "$VERSION_FILE" <<PYEOF
# Auto-generated by build-zipapp.sh — do not edit.
__version__ = "${VERSION}"
PYEOF

printf '  Generated %s\n' "_version.py"

# --- Build zipapp -----------------------------------------------------------

mkdir -p "$DIST_DIR"

python3 -m zipapp \
  "${REPO_ROOT}/src" \
  --python "/usr/bin/env python3" \
  --output "${DIST_DIR}/openstation" \
  --compress

chmod +x "${DIST_DIR}/openstation"

printf '  Built %s (%s bytes)\n' "dist/openstation" "$(wc -c < "${DIST_DIR}/openstation" | tr -d ' ')"

# --- Cleanup ----------------------------------------------------------------

rm -f "$VERSION_FILE"
printf '  Cleaned up _version.py\n'

printf '\nDone. Verify with: python3 dist/openstation --version\n'
